receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  # было localhost:4318 — это основная проблема
        include_metadata: true
      grpc:
        endpoint: "0.0.0.0:4317"


exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]  # <- сюда тоже otlp, а не jaeger
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
