version: "3"

tasks:
  
  dev-env:
    desc: "Up developer environment, docker-compose, migrations"
    cmds:
      - ./scripts/dev/dev-up.sh    
  
  dev-app:
    desc: "Run application with dev config"
    env:
      CONFIG_PATH: "./config/dev.yaml"
      POSTGRES_PASSWORD: "devpass"
    cmds:
      - go run ./cmd/payment/main.go

  dev-migrator:
    desc: "Make test migration, for local dev"
    env:
      CONFIG_PATH: "./config/dev.yaml"
      MIGRATIONS_PATH: "./tests/migrations"
    cmds:
      - ./scripts/migrator.sh

  migrator:
    desc: "Migrator for production"
    env:
      CONFIG_PATH: "./config/prod.yaml"
      MIGRATIONS_PATH: "./migrations"
    cmds:
      - ./scripts/migrator.sh
  
  run:
    desc: "Run with config file"
    env:
      CONFIG_PATH: '{{.CONFIG_PATH | default "./config/dev.yaml"}}'
      POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD | default admin123}}'
    cmds:
      - go run ./cmd/payment/main.go
    