env: "local"
grpc:
  port: 44044
  timeout: 5s
postgres:
  host: "localhost"
  port: 5432
  user: "myuser"
  dbname: "mydb"
  password: "${POSTGRES_PASSWORD}"
webhook:
  port: 8080
robokassa:
  merchantlogin: "${MERCHANT_LOGIN}"
  password1: "${PASSWORD_1}"