env: "dev"
grpc:
  port: 44044
  timeout: 5s
postgres:
  host: "localhost"
  port: 5432
  user: "admin"
  dbname: "mydatabase"
  password: "${POSTGRES_PASSWORD}"
  max_conns: 5
  conn_lifetime:
  conn_idle:
webhook:
  port: 8080
robokassa:
  merchantlogin: "${MERCHANT_LOGIN}"
  password1: "${PASSWORD_1}"