env: "dev"
grpc:
  port: 44044
  timeout: "5s"
postgres:
  host: "localhost"
  port: 5432
  user: "devuser"
  dbname: "devdb"
  password: "devpass"
redis:
  host: "localhost"
  port: 6379
  db: 0
webhook:
  port: 8080
internal:
# user for set expire time in composite, for take 
  user_TTL: "10m" 
  event_sender_TTL: "5s"
  max_name_length: 40
  max_amount: 1000000
  max_message_lenght: 200
  payment_service: "Govnokassa"
rate_limiter:
  enabled: true
  window: "30s"
  max_requests: 10
  ban_durations: ["5m", "10m", "15m", "30m", "60m"]