env: "local"
storage_path: 
grpc:
  port: 44044
postgres:
  host: "localhost"
  port: 5432
  user: "myuser"
  dbname: "mydb"
  password: "${POSTGRES_PASSWORD}"
kafka:
  brokers:
    - "localhost:9092"
  client_id: "my-app"
webhook:
  port: 8080