env: "prod"
grpc:
  port: 
  timeout: "5s"
postgres:
  host: ""
  port: 
  user: ""
  dbname: ""
  password: "${POSTGRES_PASSWORD}"
  max_conns: 
  conn_lifetime:
  conn_idle:
redis:
  host: ""
  port: 
webhook:
  port: 
internal: 
  event_sender_TTL: "5s"
  max_name_length: 40
  max_amount: 1000000
  max_message_lenght: 200
  payment_service: "Govnokassa"
# NOT IMPLEMENT
rate_limiter:
  enabled: true
  window_seconds: 30
  max_requests: 10
  ban_durations: [300, 600, 900, 1800, 3600] # seconds: 5m, 10m, 15m, 30m, 1h